/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String arg[]) {
		Library lib = new Library();
		if (lib.someLibraryMethod())
			System.out.println("I dont understand either");
			System.out.println("I am starting to understand");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
